import { router, useFocusEffect } from "expo-router";
import { ChevronLeft, FileCheck2 } from "lucide-react-native";
import { useCallback, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import api from "../../../api/api";

export default function TaxSettingsScreen() {
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const [name,setName]=useState(""); const [taxId,setTaxId]=useState(""); const [country,setCountry]=useState("India"); const [masked,setMasked]=useState("");
  useFocusEffect(useCallback(()=>{let active=true;(async()=>{try{const {data}=await api.get("/host/tax-profile");if(active){setName(data?.tax_name||"");setCountry(data?.tax_country||"India");setMasked(data?.tax_id_masked||"");}}catch(error:any){Alert.alert("Unable to load tax profile",error?.response?.data?.message||"Please try again.");}finally{if(active)setLoading(false);}})();return()=>{active=false};},[]));
  const save=async()=>{if(!name.trim()||!taxId.trim()||!country.trim()){Alert.alert("Missing details","Enter the legal name, tax ID and country.");return;}try{setSaving(true);const {data}=await api.put("/host/tax-profile",{tax_name:name.trim(),tax_id:taxId.trim(),tax_country:country.trim()});setMasked(data.tax_id_masked||"");setTaxId("");Alert.alert("Tax profile saved","Your tax information was updated securely.");}catch(error:any){Alert.alert("Save failed",error?.response?.data?.message||"Please check the details and try again.");}finally{setSaving(false)}};
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={()=>router.back()} accessibilityLabel="Go back"><ChevronLeft size={26} color="#172033"/></Pressable><Text style={styles.headerTitle}>Tax information</Text><View style={{width:26}}/></View>{loading?<ActivityIndicator style={{flex:1}} size="large" color="#3b71e6"/>:<View style={styles.content}><View style={styles.hero}><FileCheck2 size={40} color="#3b71e6"/><Text style={styles.title}>Tax profile</Text><Text style={styles.body}>Use the legal information associated with your payout account.</Text></View><Field label="Legal name" value={name} onChangeText={setName}/><Field label="Tax ID" value={taxId} onChangeText={setTaxId} placeholder={masked||"PAN, GSTIN, or local tax ID"} autoCapitalize="characters"/><Field label="Tax country" value={country} onChangeText={setCountry}/><Pressable style={[styles.button,saving&&styles.disabled]} disabled={saving} onPress={save}>{saving?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>Save tax profile</Text>}</Pressable><Text style={styles.note}>For security, the saved tax ID is displayed only by its last four characters.</Text></View>}</SafeAreaView>;
}
function Field(props:any){return <View><Text style={styles.label}>{props.label}</Text><TextInput {...props} style={styles.input} placeholderTextColor="#9aa3b2"/></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#f7f8fa"},header:{height:64,paddingHorizontal:18,backgroundColor:"#fff",flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:"#e5e7eb"},headerTitle:{fontFamily:"PlusJakartaSans_700Bold",fontSize:18,color:"#172033"},content:{padding:20,gap:15},hero:{backgroundColor:"#fff",borderRadius:24,padding:22,alignItems:"center",gap:10},title:{fontFamily:"PlusJakartaSans_700Bold",fontSize:22,color:"#172033"},body:{fontFamily:"Inter_400Regular",fontSize:13,color:"#687386",textAlign:"center"},label:{fontFamily:"Inter_600SemiBold",fontSize:12,color:"#4b5563",marginBottom:7},input:{height:52,borderWidth:1,borderColor:"#dfe3ea",borderRadius:15,backgroundColor:"#fff",paddingHorizontal:15,fontFamily:"Inter_400Regular",fontSize:14,color:"#172033"},button:{height:52,borderRadius:16,backgroundColor:"#3b71e6",alignItems:"center",justifyContent:"center"},disabled:{opacity:.5},buttonText:{fontFamily:"Inter_600SemiBold",fontSize:14,color:"#fff"},note:{fontFamily:"Inter_400Regular",fontSize:12,lineHeight:18,color:"#687386",textAlign:"center"}});
